version: "3.9"

services:
  # ---------------------------------------------------------
  # API Service (NestJS) - Development
  # ---------------------------------------------------------
  api-dev:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    container_name: hockey-scheduler-api-dev
    restart: unless-stopped
    working_dir: /app/apps/api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
    env_file:
      - ./apps/api/.env
    volumes:
      - ./apps/api:/app/apps/api
      - ./libs:/app/libs
      - /app/node_modules                # Prevent node_modules overwrite
    networks:
      - hockey-network-dev
    command: npm run start:dev


  # ---------------------------------------------------------
  # UI Service (Angular) - Development
  # ---------------------------------------------------------
  ui-dev:
    build:
      context: ./apps/web
      dockerfile: Dockerfile.dev
    container_name: hockey-scheduler-ui-dev
    restart: unless-stopped
    working_dir: /app/apps/web
    ports:
      - "4200:4200"
    environment:
      - NODE_ENV=development
    depends_on:
      - api-dev
    volumes:
      - ./apps/web:/app/apps/web
      - ./libs:/app/libs
      - /app/node_modules                # Prevent node_modules overwrite
    networks:
      - hockey-network-dev
    command: npm run start:web


# -------------------------------------------------------------
# Shared Network
# -------------------------------------------------------------
networks:
  hockey-network-dev:
    driver: bridge